<?php

/**
 * Implements hook_views_api().
 * Notifies the Views module that we're compatible with a particular API revision.
 */
function similarterms_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'similarterms') . '/views',
  );
}

/**
 * Implements hook_autoload_info().
 */
function similarterms_autoload_info() {
  return array(
    'similarterms_handler_argument_node_nid' => 'views/similarterms_handler_argument_node_nid.inc',
    'similarterms_handler_field_similar' => 'views/similarterms_handler_field_similar.inc',
    'similarterms_handler_sort_similar' => 'views/similarterms_handler_sort_similar.inc',
  );
}
